spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service_db
    #url: jdbc:mysql://host.docker.internal:3306/customer_service_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080